language: node_js

node_js:
  - "0.10"

branches:
  only:
    - master

env:
  global:
  - secure: |-
      Gz4y8zxEhPJVGfAq7UROzXS0qo9RyKFfc4hsJHy5hWBbTVCoe7BvcxtOfHkF
      6DG246MPtxvkZsqaqPUJ55eg+ED+GTyG7lWsKJb9TA/8QtqKlHSyaW9pKZgi
      Nwx1a9i7wGMCQ2GQ58KOHVAx33wpf3TVvXyEdxXNeLxDhAqlA1U=
  - secure: |-
      AjvRPOjPEuDl8qwEUOk2V1HH6C5AoE8V0/1+twsnaEcgfHWGDk3g7oPfMOW3
      ArybZFvN+wpvWfwoJAhRV7yQv9yoGT1fEtMtn3GB9mQiCFO70L/MrqXePJAr
      ajs3LH0wqhj1zW8UUmhTxBSLvzRyW++W5yx2hYr92EkrlpFZZUg=
  - LOGS_DIR=/tmp/keen-build/logs

install:
  - npm install -g grunt-cli
  - npm install

before_script:
  - mkdir -p $LOGS_DIR
  - chmod +x ./config/sauce_connect_setup.sh
  - ./config/sauce_connect_setup.sh

notifications:
  email:
    on_success: never
